version: "3.2"

services:

  tfjupyter:
    build:
      context: .
      dockerfile: Dockerfile

    #user: "1000:1000"

    ports:
      - "8888:8888"

    volumes:
      - type: bind
        source: ./covid19_pytoolbox
        target: /tf/covid19_pytoolbox
      - type: bind
        source: ./notebooks
        target: /tf/notebooks
      - type: bind
        source: ./data
        target: /tf/data
      - type: bind
        source: ./images
        target: /tf/images
      - type: bind
        source: ./applications
        target: /tf/applications

        
      - type: bind
        #password: ciao
        source: ./jupyter_notebook_config.json
        target: /home/jupuser/.jupyter/jupyter_notebook_config.json

  repiestim:
    # run the following to compute Rt based on ISS script:
    # docker-compose exec -u 1000 repiestim Rscript run_ISS_script.R
    # the result is saved in `/data/computed/ISS_Epiestim_Rt.csv`
    
    build:
      context: .
      dockerfile: Dockerfile-R

    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./R-scripts
        target: /R-scripts
      
